default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username:
  password:

development:
  <<: *default
  database: db/graphql_api_dev

test:
  <<: *default
  database: db/graphql_api_test

production:
  <<: *default
  database: db/graphql_api_prod
